import Head from "next/head";
import { useState, useEffect } from "react";

const cardImages = [
  { src: "/assets/A.png" },
  { src: "/assets/B.png" },
  { src: "/assets/C.png" },
  { src: "/assets/D.png" },
  { src: "/assets/E.png" },
  { src: "/assets/F.png" },
];

export default function Home() {
  // shuffle cards
  // const shuffledCards = cardImages.sort(() => Math.random() - 0.5);

  const [cards, setCards] = useState([]);
  const [flipped, setFlipped] = useState(0);

  const shuffleCards = () => {
    const shuffleCards = [...cardImages, ...cardImages]
      .sort(() => Math.random() - 0.5)
      .map((card, index) => ({ ...card, id: Math.random(), flip: flipped }));
    setCards(shuffleCards);
    setFlipped(0);
  };

  const cardClick = (id) => {
    setCards(
      cards.map((card) => {
        if (card.id === id) {
          card.flip = 1;
        }
        return card;
      })
    );
  };

  console.log(cards, flipped);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">Shuffle the Cards</h1>
        <button className="newGame" onClick={shuffleCards}>
          New Game
        </button>

        <div className="card-grid">
          {cards.map((card) => (
            <div className="card" key={card.id}>
              <img
                onClick={cardClick}
                className="front"
                src={card.src}
                alt="card front"
              />
              <img
                onClick={cardClick}
                className="back"
                src="/assets/Cover.png"
                alt="card back"
              />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
